targets:
  - name: Home
    sources:
      - /public/messages/en.json
    file: /public/messages/%two_letters_code%.json
    format: crowdin-json
files:
  - source: /public/messages/en.json
    translation: /%original_path%/%two_letters_code%.json
